export const STATE_STUDENT = {
  HOC: 1,
  NGHI_PHEP: 2,
  NGHI_KHONG_PHEP: 3,
};

export const SESSION = {
  MORNING: 1,
  AFTERNOON: 2,
};
export const SUBJECT = [
  {value: 'nvnc', label: 'Ngữ Văn NC'},
  {value: 'nv', label: 'Ngữ Văn'},
  {value: 'vl', label: 'Vật Lí'},
  {value: 'vlnc', label: 'Vật Lí NC'},
  {value: 'lsnc', label: 'Lịch Sử NC'},
  {value: 'ls', label: 'Lịch Sử'},
  {value: 'lsnc', label: 'Lịch Sử NC'},
  {value: 'dl', label: 'Địa Lí'},
  {value: 'dlnc', label: 'Địa Lí NC'},
  {value: 'sh', label: 'Sinh Học'},
  {value: 'shnc', label: 'Sinh Học NC'},
  {value: 'gdcd', label: 'GDCD'},
  {value: 'cn', label: 'Công Nghệ'},
  {value: 'anmt', label: 'ÂN&MT'},
  {value: 'ta', label: 'Tiếng Anh'},
  {value: 'tanc', label: 'Tiếng Anh NC'},
  {value: 'td', label: 'Thể Dục'},
  {
    value: 't',
    label: 'Toán',
  },
  {
    value: 'dsnc',
    label: 'Đại Số NC',
  },
  {value: 'ds', label: 'Đại Số'},
  {value: 'hiho', label: 'Hình Học'},
  {value: 'hihonc', label: 'Hình Học NC'},
  {value: 'hoho', label: 'Hoá Học'},
  {value: 'hohonc', label: 'Hoá Học NC'},
];
export const SUBJECTNAME = {
  anmt: 'ÂN&MT',
  cn: 'Công Nghệ',
  dl: 'Địa Lí',
  dlnc: 'Địa Lí NC',
  ds: 'Đại Số',
  dsnc: 'Đại Số NC',
  gdcd: 'GDCD',
  hiho: 'Hình Học',
  hihonc: 'Hình Học NC',
  hoho: 'Hoá Học',
  hohonc: 'Hoá Học NC',
  ls: 'Lịch Sử',
  lsnc: 'Lịch Sử NC',
  lsnc: 'Lịch Sử NC',
  nv: 'Ngữ Văn',
  nvnc: 'Ngữ Văn NC',
  sh: 'Sinh Học',
  shnc: 'Sinh Học NC',
  t: 'Toán',
  ta: 'Tiếng Anh',
  tanc: 'Tiếng Anh NC',
  td: 'Thể Dục',
  vl: 'Vật Lí',
  vlnc: 'Vật Lí NC',
};
